# Generated by Django 5.1.7 on 2025-05-15 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_managers_remove_user_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='method_payment',
            field=models.CharField(choices=[('Наличные', 'Наличные'), ('Перевод', 'Перевод')], default='Наличные', max_length=250, verbose_name='Способ оплаты'),
        ),
    ]
