# Generated by Django 5.1.7 on 2025-05-15 16:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='введите название курса', max_length=50, verbose_name='название курса')),
                ('preview', models.ImageField(blank=True, null=True, upload_to='materials/images', verbose_name='превью')),
                ('description', models.TextField(help_text='добавьте описание курса', max_length=100, verbose_name='описание')),
                ('id_stripe_product', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Название для оплаты')),
                ('price', models.IntegerField(default=0, verbose_name='Цена')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='введите название урока', max_length=50, verbose_name='название урока')),
                ('preview', models.ImageField(blank=True, null=True, upload_to='materials/images', verbose_name='превью')),
                ('description', models.TextField(blank=True, help_text='добавьте описание урока', max_length=100, null=True, verbose_name='описание')),
                ('link_to_the_video', models.URLField(blank=True, help_text='введите ссылку на видео', max_length=150, null=True, verbose_name='ссылка на видео')),
                ('id_stripe_product', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Название для оплаты')),
                ('price', models.IntegerField(default=0, verbose_name='Цена')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
            ],
            options={
                'verbose_name': 'Урок',
                'verbose_name_plural': 'Уроки',
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата начала подписки')),
            ],
            options={
                'verbose_name': 'Подписка',
                'verbose_name_plural': 'Подписки',
            },
        ),
    ]
