# Generated by Django 5.1.7 on 2025-03-23 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='введите название курса', max_length=50, verbose_name='название курса')),
                ('preview', models.ImageField(blank=True, null=True, upload_to='materials/images', verbose_name='превью')),
                ('description', models.TextField(help_text='добавьте описание курса', max_length=100, verbose_name='описание')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='введите название урока', max_length=50, verbose_name='название урока')),
                ('preview', models.ImageField(blank=True, null=True, upload_to='materials/images', verbose_name='превью')),
                ('description', models.TextField(blank=True, help_text='добавьте описание урока', max_length=100, null=True, verbose_name='описание')),
                ('link_to_the_video', models.URLField(blank=True, help_text='введите ссылку на видео', max_length=150, null=True, verbose_name='ссылка на видео')),
            ],
            options={
                'verbose_name': 'Урок',
                'verbose_name_plural': 'Уроки',
            },
        ),
    ]
